---
- assert: { that: "ansible_system_vendor == 'HP'" }

- modprobe: name=sg state=present

- name: Identifying firmware RPM for disk controller device
  shell: yum search `hpssacli ctrl all show config | grep -i smart -m 1| awk '{print $3}'` | grep -i `uname -m` | awk '{print $1}'
  register: disk_controller_rpm 
  changed_when: false

- name: Installing firmware RPM for disk controller
  yum: name={{ disk_controller_rpm.stdout }} state=latest

- name: Firmware path lookup
  shell: rpm -ql "{{ disk_controller_rpm.stdout }}" | grep '/hpsetup'
  register: FirmwarePackage 
  changed_when: false

- name: Store path to hpsetup installer
  set_fact: firmware_installer="{{ FirmwarePackage.stdout }}"

- include: firmware_installer.yml

- name: Disk controller firmware Cleanup
  yum: name={{ disk_controller_rpm.stdout }} state=absent

