---
- assert: { that: "ansible_system_vendor == 'HP'" }

- name: Identifying firmware RPM for disk drives
  shell: "yum search `hpssacli ctrl all show config detail | grep Model: | grep HP -m1 | awk '{print $NF}'` | grep -i hp-firmware | awk '{print $1}' | grep `uname  -m`"
  register: fw_rpm
  changed_when: false
  ignore_errors: yes

- include_tasks: firmware_installer.yml
  when: fw_rpm.rc == 0
