---
- name: annoying set_fact hack for fw_rpm_package
  set_fact: fw_rpm_package=" {{ fw_rpm.stdout.split(':')[0] }}"

- name: Installing firmware RPM
  yum: name={{ fw_rpm_package }}  state=latest

- name: extract path for hpsetup command
  shell: "rpm -ql {{ fw_rpm_package }}|grep /hpsetup"
  register: FirmwarePackage
  changed_when: False
  check_mode: no

- name: annoying set_fact firmware_installer path from FirmwarePackage
  set_fact: firmware_installer="{{ FirmwarePackage.stdout | splitext | first }}"

- name: Clearing previous log entries
  copy:
    content: ""
    dest: /var/cpq/Component.log
  ignore_errors: true
  changed_when: false

- name: Installing firmware in silent mode
  command: "{{ firmware_installer }} -f -s "
  ignore_errors: true

- debug: msg="Installer output {{lookup('file', '/var/cpq/Component.log') }}"

- name: Firmware RPM cleanup
  package: name={{ fw_rpm_package }} state=absent
