---
- name: Clearing previous log entries
  copy:
    content: ""
    dest: /var/cpq/Component.log
  ignore_errors: true
  changed_when: false

- name: Installing firmware in silent mode
  command: "{{ firmware_installer }} -f -s "
  ignore_errors: true

- debug: msg="Installer output {{lookup('file', '/var/cpq/Component.log') }}"
