---

- name: Clearing previous log entries
  file:
    path: "/var/cpq/Component.log"
    state: absent
  ignore_errors: true

- name: Installing firmware "{{ item }}"
  yum: name={{ item | splitext | first }}  state=latest

- name: extract path for hpsetup command
  shell: "rpm -ql {{ item }}|grep /hpsetup"
  register: FirmwarePackage
  changed_when: False
  check_mode: no

- name: annoying set_fact firmware_installer path from FirmwarePackage
  set_fact: firmware_installer="{{ FirmwarePackage.stdout | splitext | first }}"


- name: Installing firmware from "{{ item }}"  in silent mode
  command: "{{ firmware_installer }} -f -s "
  ignore_errors: true

- name: Testing if log file exists
  stat: path='/var/cpq/Component.log'
  register: optional_file

- name: Print optional installer log for "{{ item }}"
  command: "/bin/cat {{ optional_file.stat.path }}"
  register: details
  when: optional_file.stat.exists

- name: Firmware RPM cleanup
  package: name={{ item }} state=absent
