---
 - name: Identifying ILO device
   shell: lspci -v | grep -i ilo -m 1 | awk '{print $NF}' | tr A-Z a-z
   register: device 

 - name: Installing firmware RPM
   yum: name=hp-firmware-{{ device.stdout }} state=latest

 - name: Firmware path lookup 
   shell: rpm -ql hp-firmware-"{{ device.stdout }}" | grep '\.scexe'
   register: FirmwarePath

 - name: Clearing previous log entries 
   shell: "> /var/cpq/Component.log"
   ignore_errors: true

 - expect:
     command: sh "{{ FirmwarePath.stdout }}" 
     responses:
       "Continue (y/N)": 'y'

# - name: Installing ILO firmware
#   script: ../files/firmware_installer.sh --some-arguments "{{ FirmwarePath.stdout }}"
#   ignore_errors: true

 - name: Displaying Firmware installation logs
   shell: "cat /var/cpq/Component.log"
   register: InstallLog

 - debug: var=InstallLog.stdout_lines

 - name: ILO firmware Cleanup 
   yum: name=hp-firmware-{{ ILO.stdout }} state=absent
 
