---
# vim:ft=ansible:

- assert: { that: "ansible_system_vendor == 'HP'" }

- name: Checking for ILO device
  shell: hponcfg -w conf.txt|grep -i 'Firmware Revision'| awk '{print $8$9}'
  register: ilo_info
  changed_when: False
  check_mode: no

- debug:
    msg: "{{ ilo_info }}"

- name: Getting ilo version
  set_fact: ilo_version="{{ ilo_info.stdout|lower}}"

- debug:
    msg: "{{ ilo_version }}"

- name: Identifying firmware for ILO
  shell: "yum search {{ ilo_version }} |grep -i firmware"
  args:
    warn: False
  register: fw_rpm
  changed_when: False
  ignore_errors: True
  check_mode: no

- name: Starting firmware installer loop for items in "{{ fw_rpm.stdout_lines }}"
  include_tasks: firmware_installer.yml
  with_items: "{{ fw_rpm.stdout_lines }}"
  when: fw_rpm.rc == 0
