---
# vim:ft=ansible:

 - assert: { that: "ansible_system_vendor == 'HP'" }

   # We look for:
   # 01:00.0 "System peripheral" "Hewlett-Packard Company" "Integrated Lights-Out Standard Slave Instrumentation & System Support" -r05 "Hewlett-Packard Company" "iLO4"
 - name: Checking for ILO device
   command: lspci -s 01:00.0 -m
   register: ilo_info
   changed_when: False

   # We need to get the "iLO4" from the above into a varible
   # using the python split fuction on the '"' character and the 2nd from last
   # element of the resulting array. "|lower" is a Jinja2 filter
 - name: Getting ilo version
   set_fact: ilo_version={{ ilo_info.stdout.split('\"')[-2] |lower}}

 - assert: { that: ilo_version | match("ilo4") }

 - name: Installing firmware RPM
   yum: name=hp-firmware-{{ ilo_version }} state=latest

 - name: Firmware path lookup 
   command: rpm -q hp-firmware-"{{ ilo_version }}"
   register: FirmwarePackage
   changed_when: False

 - name: Store path to hpsetup installer
   set_fact: firmware_installer="/usr/lib/i386-linux-gnu/{{ FirmwarePackage.stdout | splitext | first }}/hpsetup"

 - name: Clearing previous log entries 
   shell: "> /var/cpq/Component.log"
   ignore_errors: true

 - name: Installing firmware
   expect:
     command: "{{ firmware_installer }}" 
     timeout: 600 
     responses:
       "Continue (y/N)?": "y"
   register: upgrade_results
   changed_when: upgrade_results.rc == 0
   failed_when: upgrade_results.rc != 2

 - debug: var=upgrade_results

 - name: Displaying Firmware installation logs
   shell: "cat /var/cpq/Component.log"
   register: InstallLog
   changed_when: False

 - debug: var=InstallLog.stdout_lines
