---
  - name: Installing firmware RPM for System ROM
    shell: yum install -y hp-firmware-system-`hp-conrep -s | grep -i family | awk '{print $NF}' | tr A-Z a-z` 
 
  - name: Installing firmware RPM for ILO
    shell: yum install -y hp-firmware-`lspci -v | grep -i ilo -m 1 | awk '{print $NF}' | tr A-Z a-z`
  
  - name: Installing firmware RPM for Power Mangement Controller
    shell: yum install -y hp-firmware-powerpic-`hp-conrep -s | grep  "System Type" | awk '{print $NF}' | tr A-Z a-z`

  - name: Installing firmware RPM for Smart Array disk controller [step 1/2] 
    shell: yum search `hpacucli ctrl all show config | grep -i smart -m 1| awk '{print $3}'` | grep -i `uname -m` | awk '{print $1}'
    register: smartarray

  - name: Installing firmware RPM for Smart Array disk controller [step 2/2]
    shell: yum install -y {{ smartarray.stdout }}

  - name: Installing firmware RPM for Disk Drive [step 1/2]
    shell: yum search `hpacucli ctrl all show config detail|grep physicaldrive -A15 | grep -i model -m1 | awk '{print $NF}'` | grep -i hp-firmware | awk '{print $1}'
    register: diskdrive

  - name: Installing firmware RPM for Disk Drive [step 2/2]
    shell: yum install -y {{ diskdrive.stdout }}

  - name: Installing firwmare RPM for Network Device of type Intel [step 1/2]  
    shell: lspci -v |grep Ethernet | grep -i intel -m 1
    register: ethernetdevice
 
  - name: Installing firwmare RPM for Network Device of type Intel [step 2/2]
    shell: yum install -y hp-firmware-nic-intel
    when: ethernetdevice.stdout != " "

  - name: Installing firwmare RPM for Network Device of type Mellanox [step 1/2]
    shell: lspci -v |grep -i Mellanox -m 1 
    register: mellanoxdevice

  - name: Installing firwmare RPM for Network Device of type Mellanox [step 2/2]
    shell: yum install -y hp-firmware-hca-mellanox-vpi-eth-ib
    when: mellanoxdevice.stdout != " "
 
    

