---

- include: prerequisite.yml 
  tags:
    - ilo
    - system-rom
    - disk-controller

- include: ilo.yml
  tags:
    - ilo

- include: system_rom.yml 
  tags:
   - system-rom

- include: disk_controller.yml
  tags:
   - disk-controller 

