---

- include: prerequisite.yml 
  tags:
    - ilo
    - system-rom
    - disk-controller
    - disk-drive

- include: ilo.yml
  tags:
    - ilo

- include: system_rom.yml 
  tags:
   - system-rom

- include: disk_controller.yml
  tags:
   - disk-controller 

- include: disk_drive.yml
  tags:
   - disk-drive

