---
- assert: { that: "ansible_system_vendor == 'HP'" }

- name: Installing firmware RPM for Mellanox Network adapter 
  yum: name=hp-firmware-hca-mellanox-vpi-eth-ib state=latest

- name: Firmware path lookup
  shell: rpm -ql hp-firmware-hca-mellanox-vpi-eth-ib | grep '/hpsetup'
  register: FirmwarePackage 
  changed_when: false

- name: Store path to hpsetup installer
  set_fact: firmware_installer="{{ FirmwarePackage.stdout }}"

- name: Clearing previous log entries
  shell: "> /var/cpq/Component.log"
  ignore_errors: true
  changed_when: false

- name: Installing firmware
  command: "{{ firmware_installer }} -y "
  ignore_errors: true

- name: Displaying Firmware installation logs
  shell: "cat /var/cpq/Component.log"
  register: InstallLog
  changed_when: false

- debug: var=InstallLog.stdout_lines

- name: Mellanox Network adapter firmware Cleanup
  yum: name=hp-firmware-hca-mellanox-vpi-eth-ib state=absent

