---
- assert: { that: "ansible_system_vendor == 'HP'" }

- name: Identifying firmware RPM for Mellanox Network Adapter
  shell: "yum search hp-firmware-hca-mellanox-vpi-eth-ib |grep hp-firmware-hca-mellanox-vpi-eth-ib"
  register: fw_rpm
  changed_when: False
  ignore_errors: True
  check_mode: no

- name: running generic tasks for all firmware things
  include_tasks: firmware_installer.yml
  with_items: "{{ fw_rpm.stdout_lines }}"
  when: fw_rpm.rc == 0
