---

 - name: Identifying System ROM device
   shell: hp-conrep -s | grep -i family | awk '{print $NF}' | tr A-Z a-z
   register: systemrom
   check_mode: no

 - name: Identifying firmware RPM for System ROM
   shell: "yum search firmware-system-{{ systemrom.stdout }} | grep hp-firmware-system"
   register: fw_rpm
   changed_when: False
   ignore_errors: True
   check_mode: no

 - include: firmware_installer.yml
   when: fw_rpm.rc == 0
