---
 - name: Identifying System ROM device
   shell: hp-conrep -s | grep -i family | awk '{print $NF}' | tr A-Z a-z
   register: systemrom

 - name: Installing firmware RPM for System ROM
   yum: name=hp-firmware-system-{{ systemrom.stdout }} state=latest

 - name: Firmware path lookup
   shell: rpm -ql hp-firmware-system-"{{ systemrom.stdout }}" | grep '\.scexe'
   register: FirmwarePath

 - name: Clearing previous log entries
   shell: "> /var/cpq/Component.log"
   ignore_errors: true
   changed_when: false

 - name: Install firmware
   expect:
     command: "{{ FirmwarePath.stdout }}"
     timeout: 1200 
     responses:
       "Do you want to upgrade the software to a newer version.*": "y"
       "Do you want to reboot your system now.*": "n"

 - name: Displaying Firmware installation logs
   shell: "cat /var/cpq/Component.log"
   register: InstallLog
   changed_when: false

 - debug: var=InstallLog.stdout_lines

 - name: System ROM firmware Cleanup
   yum: name=hp-firmware-{{ systemrom.stdout }} state=absent

