---
 - name: Identifying System ROM device
   shell: hp-conrep -s | grep -i family | awk '{print $NF}' | tr A-Z a-z
   register: systemrom

 - name: Installing firmware RPM for System ROM
   yum: name=hp-firmware-system-{{ systemrom.stdout }} state=latest

 - name: Firmware path lookup
   command: rpm -q hp-firmware-system-"{{ systemrom.stdout }}" 
   register: FirmwarePackage
   changed_when: False

 - name: Store path to hpsetup installer
   set_fact: firmware_installer="/usr/lib/i386-linux-gnu/{{ FirmwarePackage.stdout | splitext | first }}/hpsetup"

 - include: firmware_installer.yml

 - name: System ROM firmware Cleanup
   yum: name=hp-firmware-system-{{ systemrom.stdout }} state=absent

